### ISSUE TITLE
Setup automatic error reporting

### ISSUE THREAD

**Issue by smehrbrodt** [LibreOffice/loeclipse#47]
https://ctrlflow.com/automated-error-reporting/

**Comment by JohannesDorn** [comment]
Hi,

I am one of the developers of Automated Error Reporting.
I've noticed that you have already set up an account with us but haven't send any error reports, yet.

Due to your removal of the "easy-hack" tag, can I assume that you tried to integrate error reporting but it didn't work?

If so, this may have been due to a missing dependency in your MANIFEST.MF file.
We have since clarified our documentation; I am sorry if it hasn't been clear enough in the past.

To try again, simply follow the guide on your service’s [client configurations](https://aer.ctrlflow.com/loeclipse/reviewers#!/client-configurations) page and it should work.

If you want I could also make a pull request that adds Automated Error Reporting.

**Comment by smehrbrodt** [comment]
I added the stuff to the "core" plugin, can you please check if it's accurate?

This project contains 2 plugins, can I add the same thing for the "java" plugin?

**Comment by JohannesDorn** [comment]
It does indeed look accurate.

It is not necessary to configure the extension point again for a the "java" plugin.
Errors reported in either will be sent to your error reporting service.

A separate configuration would only be needed if you wanted to send errors from different plugins to different, or if one plugin could be installed without the other.

In the latter case I would suggest introducing a minimal plugin that configures the error reporting which would always be installed along with any other plugin. But I think in your case, you won't need to do that.

**Comment by smehrbrodt** [comment]
Thanks, will release a new version.
Lets see if errors will be reported then.

**Comment by JohannesDorn** [comment]
Indeed they are :)

I did a quick test and managed to get a NullPointerException in the LibreOffice plugin and reported it.

**Comment by smehrbrodt** [comment]
Nice :)
